### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [PonderingGrower/rbackup#2]
Hello,

Your code seems to be improperly licensed; I urge you to adopt the GPLv3 License which is the only license to truly respect freedom, making it the only viable license for any FOSS development. Making a donation to the FSF would also be welcome.

https://www.gnu.org/licenses/quick-guide-gplv3.html
https://www.gnu.org/licenses/gpl-howto.html

**Comment by jakubgs** [comment]
I defaulted to the license most Python projects use since I don't know much about licensing in the first place.

Before I release 0.1 I intend to read up a bit more on licensing for sure.

**Comment by jakubgs** [comment]
I found this which apparently helps to select a license:
https://choosealicense.com/
I'll play with it later.

**Comment by jakubgs** [comment]
For simplicity I'm torn between MIT and BSD 3 licenses. They are short and to then point.
But I do kinda like the idea that any forks of this software would have to be GPL 3.0 if I chose it, but I's not mandatory. Especially since this is a very simple utility.

**Comment by jakubgs** [comment]
I'm gonna go with BSD 3 since it clearly states 

>Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Which I like.
